package spp.protocol.insight

enum class InsightType {
    METHOD_DURATION,
    METHOD_CALL_PROBABILITY,
    LOOP_ITERATION_AVG,
    LOOP_ITERATION_MAX,
    LOOP_ITERATION_MIN,
    LOOP_ITERATION_STDDEV,
    LOOP_ITERATION_SUM,
    LOOP_ITERATION_VARIANCE,
    LOOP_DURATION_AVG,
    LOOP_DURATION_MAX,
    LOOP_DURATION_MIN,
    LOOP_DURATION_STDDEV,
    LOOP_DURATION_SUM,
    LOOP_DURATION_VARIANCE,
}
